MONGO_DB = 'db_tts'
MONGO_USERS_COLLECTION = 'users'
MONGO_KARYAWAN_COLLECTION = 'karyawan'
MONGO_KATEGORI_COLLECTION = 'kategori'
MONGO_BRAND_COLLECTION = 'brand'
MONGO_PRODUK_COLLECTION = 'produk'
MONGO_MEMBERSHIP_COLLECTION = 'membership'
MONGO_SUPPLIER_COLLECTION = 'supplier'
MONGO_PENGELUARAN_COLLECTION = 'transaksi_pengeluaran'
MONGO_PEMBELIAN_COLLECTION = 'transaksi_pembelian'
MONGO_DETAIL_PEMBELIAN_COLLECTION = 'detail_pembelian'
MONGO_PENJUALAN_COLLECTION = 'penjualan'

UPLOAD_FOLDER = 'D:\Perkuliahan\Semester 9\Kapita Selekta\Foto'
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}

MONGO_URI = ''
